# Generated by Django 4.2.18 on 2025-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_exemplar_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='exclos_prestec',
            field=models.BooleanField(default=False),
        ),
    ]
