# Generated by Django 4.2.18 on 2025-04-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_exemplar_exclos_prestec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplar',
            options={'ordering': ['registre'], 'verbose_name': 'Exemplar', 'verbose_name_plural': 'Exemplars'},
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.centre', verbose_name='Centre'),
        ),
    ]
