# Generated by Django 4.2 on 2025-04-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_alter_exemplar_options_alter_exemplar_centre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cicle',
            new_name='Grup',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='cicle',
            new_name='Grup',
        ),
    ]
