# Generated by Django 5.2.1 on 2025-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_alter_exemplar_options_alter_exemplar_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
