# Generated by Django 4.2 on 2025-04-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_rename_cicle_grup_rename_cicle_usuari_grup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuari',
            old_name='Grup',
            new_name='grup',
        ),
    ]
