# Generated by Django 4.2.18 on 2025-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_rename_grup_usuari_grup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='registre',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
